use lab_apis::core::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Show the schema for a specific action",
        destructive: false,
        returns: "ActionSpec",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Name of the action to show the schema for",
        }],
    },
    ActionSpec {
        name: "transfer.info",
        description: "Get global transfer info (speeds, limits, DHT nodes, connection status)",
        destructive: false,
        returns: "TransferInfo",
        params: &[],
    },
    ActionSpec {
        name: "transfer.download.limit",
        description: "Set global download speed limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "limit",
            ty: "integer",
            required: true,
            description: "Download speed limit in bytes/s (0 to remove limit)",
        }],
    },
    ActionSpec {
        name: "transfer.upload.limit",
        description: "Set global upload speed limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "limit",
            ty: "integer",
            required: true,
            description: "Upload speed limit in bytes/s (0 to remove limit)",
        }],
    },
    ActionSpec {
        name: "torrent.list",
        description: "List torrents, optionally filtered by state or category",
        destructive: false,
        returns: "Torrent[]",
        params: &[
            ParamSpec {
                name: "filter",
                ty: "string",
                required: false,
                description: "State filter: all | downloading | seeding | completed | paused | active | inactive | resumed | stalled | errored",
            },
            ParamSpec {
                name: "category",
                ty: "string",
                required: false,
                description: "Filter by category name",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: false,
                description: "Max number of torrents to return",
            },
        ],
    },
    ActionSpec {
        name: "torrent.properties",
        description: "Get detailed properties of a torrent by hash",
        destructive: false,
        returns: "TorrentProperties",
        params: &[ParamSpec {
            name: "hash",
            ty: "string",
            required: true,
            description: "Torrent info hash",
        }],
    },
    ActionSpec {
        name: "torrent.trackers",
        description: "Get tracker list for a torrent by hash",
        destructive: false,
        returns: "Tracker[]",
        params: &[ParamSpec {
            name: "hash",
            ty: "string",
            required: true,
            description: "Torrent info hash",
        }],
    },
    ActionSpec {
        name: "torrent.pause",
        description: "Pause one or more torrents (pipe-separated hashes, or 'all')",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.resume",
        description: "Resume one or more torrents (pipe-separated hashes, or 'all')",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.delete",
        description: "Delete one or more torrents and optionally their data",
        destructive: true,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "delete_files",
                ty: "bool",
                required: false,
                description: "Also delete downloaded data (default: false)",
            },
        ],
    },
    ActionSpec {
        name: "torrent.recheck",
        description: "Force re-hash verification of one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.category.set",
        description: "Set the category for one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "category",
                ty: "string",
                required: true,
                description: "Category name to assign",
            },
        ],
    },
    ActionSpec {
        name: "torrent.download.limit",
        description: "Set per-torrent download limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: true,
                description: "Download speed limit in bytes/s (0 to remove limit)",
            },
        ],
    },
    ActionSpec {
        name: "torrent.upload.limit",
        description: "Set per-torrent upload limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: true,
                description: "Upload speed limit in bytes/s (0 to remove limit)",
            },
        ],
    },
    ActionSpec {
        name: "categories.list",
        description: "List all torrent categories",
        destructive: false,
        returns: "Category[]",
        params: &[],
    },
    ActionSpec {
        name: "app.version",
        description: "Get the qBittorrent application version",
        destructive: false,
        returns: "string",
        params: &[],
    },
    ActionSpec {
        name: "app.preferences",
        description: "Get application preferences (save path, rate limits, slot limits)",
        destructive: false,
        returns: "Preferences",
        params: &[],
    },
    ActionSpec {
        name: "log.list",
        description: "Get application log entries",
        destructive: false,
        returns: "LogEntry[]",
        params: &[ParamSpec {
            name: "last_known_id",
            ty: "integer",
            required: false,
            description: "Return only entries after this log ID (-1 = all entries)",
        }],
    },
    ActionSpec {
        name: "torrent.add",
        description: "Add one or more torrents by URL (magnet links or HTTP URLs, newline-separated)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "urls",
                ty: "string",
                required: true,
                description: "Newline-separated magnet links or HTTP torrent URLs",
            },
            ParamSpec {
                name: "savepath",
                ty: "string",
                required: false,
                description: "Override save path for added torrent(s)",
            },
            ParamSpec {
                name: "category",
                ty: "string",
                required: false,
                description: "Category to assign to added torrent(s)",
            },
            ParamSpec {
                name: "tags",
                ty: "string",
                required: false,
                description: "Comma-separated tags to assign to added torrent(s)",
            },
        ],
    },
    ActionSpec {
        name: "transfer.toggle-speed-limits",
        description: "Toggle alternative speed limits mode on/off",
        destructive: false,
        returns: "{}",
        params: &[],
    },
    ActionSpec {
        name: "torrent.files",
        description: "Get the file list for a torrent by hash",
        destructive: false,
        returns: "TorrentFile[]",
        params: &[ParamSpec {
            name: "hash",
            ty: "string",
            required: true,
            description: "Torrent info hash",
        }],
    },
    ActionSpec {
        name: "torrent.set-file-prio",
        description: "Set the download priority for a specific file within a torrent",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hash",
                ty: "string",
                required: true,
                description: "Torrent info hash",
            },
            ParamSpec {
                name: "id",
                ty: "string",
                required: true,
                description: "Pipe-separated file indices within the torrent",
            },
            ParamSpec {
                name: "priority",
                ty: "integer",
                required: true,
                description: "Priority: 0=do not download, 1=normal, 6=high, 7=maximum",
            },
        ],
    },
    ActionSpec {
        name: "torrent.set-location",
        description: "Move one or more torrents to a new save location",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "location",
                ty: "string",
                required: true,
                description: "New absolute save path",
            },
        ],
    },
    ActionSpec {
        name: "torrent.add-tags",
        description: "Add tags to one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "tags",
                ty: "string",
                required: true,
                description: "Comma-separated tag names to add",
            },
        ],
    },
    ActionSpec {
        name: "torrent.remove-tags",
        description: "Remove tags from one or more torrents (empty tags string removes all tags)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "tags",
                ty: "string",
                required: true,
                description: "Comma-separated tag names to remove (empty = remove all)",
            },
        ],
    },
    ActionSpec {
        name: "torrent.reannounce",
        description: "Force re-announce one or more torrents to all their trackers",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.set-share-limits",
        description: "Set ratio and seeding time share limits for one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "ratio_limit",
                ty: "number",
                required: true,
                description: "Ratio limit (-2=global, -1=no limit, ≥0=cap)",
            },
            ParamSpec {
                name: "seeding_time_limit",
                ty: "integer",
                required: true,
                description: "Seeding time limit in minutes (-2=global, -1=no limit, ≥0=cap)",
            },
            ParamSpec {
                name: "inactive_seeding_time_limit",
                ty: "integer",
                required: true,
                description: "Inactive seeding time limit in minutes (-2=global, -1=no limit, ≥0=cap)",
            },
        ],
    },
    ActionSpec {
        name: "category.create",
        description: "Create a new torrent category",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "category",
                ty: "string",
                required: true,
                description: "New category name",
            },
            ParamSpec {
                name: "savepath",
                ty: "string",
                required: false,
                description: "Default save path for this category",
            },
        ],
    },
    ActionSpec {
        name: "category.edit",
        description: "Edit an existing torrent category's save path",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "category",
                ty: "string",
                required: true,
                description: "Existing category name to edit",
            },
            ParamSpec {
                name: "savepath",
                ty: "string",
                required: true,
                description: "New default save path for this category",
            },
        ],
    },
    ActionSpec {
        name: "sync.maindata",
        description: "Get sync maindata (full state or incremental delta). Callers must store and pass back the rid from the previous response for incremental delta updates.",
        destructive: false,
        returns: "SyncMaindata",
        params: &[ParamSpec {
            name: "rid",
            ty: "integer",
            required: false,
            description: "Response ID from previous call (0 or omit for full dump; pass returned rid for delta updates)",
        }],
    },
];
