use lab_apis::core::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Show the schema for a specific action",
        destructive: false,
        returns: "ActionSpec",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Name of the action to show the schema for",
        }],
    },
    ActionSpec {
        name: "transfer.info",
        description: "Get global transfer info (speeds, limits, DHT nodes, connection status)",
        destructive: false,
        returns: "TransferInfo",
        params: &[],
    },
    ActionSpec {
        name: "transfer.download.limit",
        description: "Set global download speed limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "limit",
            ty: "integer",
            required: true,
            description: "Download speed limit in bytes/s (0 to remove limit)",
        }],
    },
    ActionSpec {
        name: "transfer.upload.limit",
        description: "Set global upload speed limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "limit",
            ty: "integer",
            required: true,
            description: "Upload speed limit in bytes/s (0 to remove limit)",
        }],
    },
    ActionSpec {
        name: "torrent.list",
        description: "List torrents, optionally filtered by state or category",
        destructive: false,
        returns: "Torrent[]",
        params: &[
            ParamSpec {
                name: "filter",
                ty: "string",
                required: false,
                description: "State filter: all | downloading | seeding | completed | paused | active | inactive | resumed | stalled | errored",
            },
            ParamSpec {
                name: "category",
                ty: "string",
                required: false,
                description: "Filter by category name",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: false,
                description: "Max number of torrents to return",
            },
        ],
    },
    ActionSpec {
        name: "torrent.properties",
        description: "Get detailed properties of a torrent by hash",
        destructive: false,
        returns: "TorrentProperties",
        params: &[ParamSpec {
            name: "hash",
            ty: "string",
            required: true,
            description: "Torrent info hash",
        }],
    },
    ActionSpec {
        name: "torrent.trackers",
        description: "Get tracker list for a torrent by hash",
        destructive: false,
        returns: "Tracker[]",
        params: &[ParamSpec {
            name: "hash",
            ty: "string",
            required: true,
            description: "Torrent info hash",
        }],
    },
    ActionSpec {
        name: "torrent.pause",
        description: "Pause one or more torrents (pipe-separated hashes, or 'all')",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.resume",
        description: "Resume one or more torrents (pipe-separated hashes, or 'all')",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.delete",
        description: "Delete one or more torrents and optionally their data",
        destructive: true,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "delete_files",
                ty: "bool",
                required: false,
                description: "Also delete downloaded data (default: false)",
            },
        ],
    },
    ActionSpec {
        name: "torrent.recheck",
        description: "Force re-hash verification of one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[ParamSpec {
            name: "hashes",
            ty: "string",
            required: true,
            description: "Pipe-separated torrent hashes or 'all'",
        }],
    },
    ActionSpec {
        name: "torrent.category.set",
        description: "Set the category for one or more torrents",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "category",
                ty: "string",
                required: true,
                description: "Category name to assign",
            },
        ],
    },
    ActionSpec {
        name: "torrent.download.limit",
        description: "Set per-torrent download limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: true,
                description: "Download speed limit in bytes/s (0 to remove limit)",
            },
        ],
    },
    ActionSpec {
        name: "torrent.upload.limit",
        description: "Set per-torrent upload limit in bytes/s (0 = unlimited)",
        destructive: false,
        returns: "{}",
        params: &[
            ParamSpec {
                name: "hashes",
                ty: "string",
                required: true,
                description: "Pipe-separated torrent hashes or 'all'",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: true,
                description: "Upload speed limit in bytes/s (0 to remove limit)",
            },
        ],
    },
    ActionSpec {
        name: "categories.list",
        description: "List all torrent categories",
        destructive: false,
        returns: "Category[]",
        params: &[],
    },
    ActionSpec {
        name: "app.version",
        description: "Get the qBittorrent application version",
        destructive: false,
        returns: "string",
        params: &[],
    },
    ActionSpec {
        name: "app.preferences",
        description: "Get application preferences (save path, rate limits, slot limits)",
        destructive: false,
        returns: "Preferences",
        params: &[],
    },
    ActionSpec {
        name: "log.list",
        description: "Get application log entries",
        destructive: false,
        returns: "LogEntry[]",
        params: &[ParamSpec {
            name: "last_known_id",
            ty: "integer",
            required: false,
            description: "Return only entries after this log ID (-1 = all entries)",
        }],
    },
];
