pub mod acp;
#[cfg(feature = "apprise")]
pub mod apprise;
#[cfg(feature = "arcane")]
pub mod arcane;
#[cfg(feature = "bytestash")]
pub mod bytestash;
pub mod clients;
#[cfg(feature = "deploy")]
pub mod deploy;
pub mod doctor;
#[cfg(feature = "dozzle")]
pub mod dozzle;
pub mod error;
pub mod extract;
#[cfg(feature = "freshrss")]
pub mod freshrss;
pub mod fs;
pub mod gateway;
#[cfg(feature = "gotify")]
pub mod gotify;
pub mod helpers;
#[cfg(feature = "uptime_kuma")]
pub mod uptime_kuma;
#[cfg(feature = "glances")]
pub mod glances;
#[cfg(feature = "adguard")]
pub mod adguard;
#[cfg(feature = "immich")]
pub mod immich;
pub mod lab_admin;
#[cfg(feature = "linkding")]
pub mod linkding;
#[cfg(feature = "loggifly")]
pub mod loggifly;
pub mod logs;
pub mod marketplace;
#[cfg(feature = "memos")]
pub mod memos;
#[cfg(feature = "navidrome")]
pub mod navidrome;
pub mod node;
#[cfg(feature = "notebooklm")]
pub mod notebooklm;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "overseerr")]
pub mod overseerr;
#[cfg(feature = "paperless")]
pub mod paperless;
pub mod path_safety;
#[cfg(feature = "plex")]
pub mod plex;
#[cfg(feature = "prowlarr")]
pub mod prowlarr;
#[cfg(feature = "qbittorrent")]
pub mod qbittorrent;
#[cfg(feature = "qdrant")]
pub mod qdrant;
#[cfg(feature = "radarr")]
pub mod radarr;
pub mod redact;
#[cfg(feature = "sabnzbd")]
pub mod sabnzbd;
#[cfg(feature = "scrutiny")]
pub mod scrutiny;
pub mod setup;
#[cfg(feature = "sonarr")]
pub mod sonarr;
pub mod stash;
#[cfg(feature = "tailscale")]
pub mod tailscale;
#[cfg(feature = "tautulli")]
pub mod tautulli;
#[cfg(feature = "tei")]
pub mod tei;
#[cfg(feature = "unifi")]
pub mod unifi;
#[cfg(feature = "unraid")]
pub mod unraid;
pub mod upstream;
