#[cfg(feature = "apprise")]
pub mod apprise;
#[cfg(feature = "arcane")]
pub mod arcane;
#[cfg(feature = "bytestash")]
pub mod bytestash;
pub mod clients;
#[cfg(feature = "deploy")]
pub mod deploy;
pub mod error;
pub mod extract;
pub mod gateway;
#[cfg(feature = "gotify")]
pub mod gotify;
pub mod helpers;
pub mod lab_admin;
#[cfg(feature = "linkding")]
pub mod linkding;
pub mod logs;
#[cfg(feature = "mcpregistry")]
pub mod mcpregistry;
#[cfg(feature = "memos")]
pub mod memos;
#[cfg(feature = "openai")]
pub mod openai;
#[cfg(feature = "overseerr")]
pub mod overseerr;
#[cfg(feature = "paperless")]
pub mod paperless;
#[cfg(feature = "plex")]
pub mod plex;
#[cfg(feature = "prowlarr")]
pub mod prowlarr;
#[cfg(feature = "qbittorrent")]
pub mod qbittorrent;
#[cfg(feature = "qdrant")]
pub mod qdrant;
#[cfg(feature = "radarr")]
pub mod radarr;
pub mod redact;
#[cfg(feature = "sabnzbd")]
pub mod sabnzbd;
#[cfg(feature = "sonarr")]
pub mod sonarr;
#[cfg(feature = "tailscale")]
pub mod tailscale;
#[cfg(feature = "tautulli")]
pub mod tautulli;
#[cfg(feature = "tei")]
pub mod tei;
#[cfg(feature = "unifi")]
pub mod unifi;
#[cfg(feature = "unraid")]
pub mod unraid;
pub mod upstream;
