import type { McpServer, AcpAgent } from './types'

export const MOCK_MCP_SERVERS: McpServer[] = [
  {
    name: 'filesystem',
    description: 'Read and write files on the local filesystem with configurable access controls.',
    version: '0.6.2',
    package: '@modelcontextprotocol/server-filesystem',
    transport: ['stdio'],
  },
  {
    name: 'github',
    description: 'Interact with GitHub repositories, issues, pull requests, and workflows.',
    version: '0.4.1',
    package: '@modelcontextprotocol/server-github',
    transport: ['stdio'],
  },
  {
    name: 'memory',
    description: 'Persistent key-value memory store for long-running agent sessions.',
    version: '0.3.0',
    package: '@modelcontextprotocol/server-memory',
    transport: ['stdio', 'sse'],
  },
  {
    name: 'brave-search',
    description: 'Web and local search via the Brave Search API.',
    version: '0.2.0',
    package: '@modelcontextprotocol/server-brave-search',
    transport: ['stdio'],
  },
]

export const MOCK_ACP_AGENTS: AcpAgent[] = [
  { id: 'amp-acp', name: 'Amp', version: '0.7.0', description: 'ACP wrapper for Amp - the frontier coding agent', distribution: { binary: {} } },
  { id: 'auggie', name: 'Auggie CLI', version: '0.24.0', description: "Augment Code's software agent, backed by its context engine.", distribution: { npx: {} } },
  { id: 'autohand', name: 'Autohand Code', version: '0.2.1', description: 'AI coding agent powered by Autohand AI.', distribution: { npx: {} } },
  { id: 'claude-acp', name: 'Claude Agent', version: '0.31.0', description: "ACP wrapper for Anthropic's Claude.", distribution: { npx: {} } },
  { id: 'cline', name: 'Cline', version: '2.17.0', description: 'Autonomous coding agent CLI for editing files, running commands, and browser use.', distribution: { npx: {} } },
  { id: 'codebuddy-code', name: 'Codebuddy Code', version: '2.93.6', description: "Tencent Cloud's official intelligent coding tool.", distribution: { npx: {} } },
  { id: 'codex-acp', name: 'Codex CLI', version: '0.12.0', description: "ACP adapter for OpenAI's coding assistant.", distribution: { binary: {} } },
  { id: 'corust-agent', name: 'Corust Agent', version: '0.5.1', description: 'Co-building with a seasoned Rust partner.', distribution: { binary: {} } },
  { id: 'crow-cli', name: 'crow-cli', version: '0.1.19', description: 'Minimal ACP Native Coding Agent.', distribution: { binary: {} } },
  { id: 'cursor', name: 'Cursor', version: '2026.03.30', description: "Cursor's coding agent.", distribution: { binary: {} } },
  { id: 'deepagents', name: 'DeepAgents', version: '0.1.7', description: 'Batteries-included AI coding and general purpose agent powered by LangChain.', distribution: { npx: {} } },
  { id: 'factory-droid', name: 'Factory Droid', version: '0.109.1', description: 'AI coding agent powered by Factory AI.', distribution: { npx: {} } },
  { id: 'fast-agent', name: 'fast-agent', version: '0.6.24', description: 'Code and build agents with comprehensive multi-provider support.', distribution: { uvx: {} } },
  { id: 'gemini', name: 'Gemini CLI', version: '0.39.1', description: "Google's official CLI for Gemini.", distribution: { npx: {} } },
  { id: 'github-copilot-cli', name: 'GitHub Copilot', version: '1.0.36', description: "GitHub's AI pair programmer.", distribution: { npx: {} } },
  { id: 'goose', name: 'goose', version: '1.32.0', description: 'A local, extensible, open source AI agent that automates engineering tasks.', distribution: { binary: {} } },
  { id: 'junie', name: 'Junie', version: '1417.47.0', description: 'AI Coding Agent by JetBrains.', distribution: { binary: {} } },
  { id: 'kilo', name: 'Kilo', version: '7.2.22', description: 'The open source coding agent.', distribution: { binary: {} } },
  { id: 'kimi', name: 'Kimi CLI', version: '1.39.0', description: "Moonshot AI's coding assistant.", distribution: { binary: {} } },
  { id: 'minion-code', name: 'Minion Code', version: '0.1.44', description: 'Enhanced AI code assistant built on the Minion framework.', distribution: { uvx: {} } },
  { id: 'mistral-vibe', name: 'Mistral Vibe', version: '2.8.1', description: "Mistral's open-source coding assistant.", distribution: { binary: {} } },
  { id: 'nova', name: 'Nova', version: '1.0.100', description: 'Nova by Compass AI - a software engineer at your command.', distribution: { npx: {} } },
  { id: 'opencode', name: 'OpenCode', version: '1.14.24', description: 'The open source coding agent.', distribution: { binary: {} } },
  { id: 'pi-acp', name: 'pi ACP', version: '0.0.26', description: 'ACP adapter for pi coding agent.', distribution: { npx: {} } },
  { id: 'qoder', name: 'Qoder CLI', version: '0.1.48', description: 'AI coding assistant with agentic capabilities.', distribution: { npx: {} } },
  { id: 'qwen-code', name: 'Qwen Code', version: '0.15.2', description: "Alibaba's Qwen coding assistant.", distribution: { npx: {} } },
  { id: 'stakpak', name: 'Stakpak', version: '0.3.74', description: 'Open-source DevOps agent in Rust with enterprise-grade security.', distribution: { binary: {} } },
]
