#!/usr/bin/env bash
# Install and start the gh-webhook user-level systemd unit.
#
# - Generates a 32-byte random shared secret on first run (openssl rand -hex 32).
# - Writes ~/.config/gh-webhook/env with mode 0600.
# - Installs the systemd user unit and enables+starts it.
# - Prints the webhook URL and secret for manual registration.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIT_SRC="${SCRIPT_DIR}/../systemd/gh-webhook.service"

CONFIG_DIR="${HOME}/.config/gh-webhook"
ENV_FILE="${CONFIG_DIR}/env"
DATA_DIR="${HOME}/.local/share/gh-webhook"
SERVICE_DIR="${HOME}/.config/systemd/user"
SERVICE_FILE="${SERVICE_DIR}/gh-webhook.service"

mkdir -p "${CONFIG_DIR}" "${DATA_DIR}" "${SERVICE_DIR}"
chmod 700 "${CONFIG_DIR}" "${DATA_DIR}"

if [[ ! -f "${ENV_FILE}" ]]; then
  if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl is required to generate the webhook secret" >&2
    exit 1
  fi
  secret="$(openssl rand -hex 32)"
  umask 077
  cat > "${ENV_FILE}" <<EOF
# gh-webhook configuration — generated by install-systemd.sh
# Edit GH_WEBHOOK_GITHUB_TOKEN before calling gh-webhook-register.
GH_WEBHOOK_SECRET=${secret}
GH_WEBHOOK_GITHUB_TOKEN=REPLACE_ME
GH_WEBHOOK_DATA_DIR=${DATA_DIR}
GH_WEBHOOK_BIND=127.0.0.1:7891
GH_WEBHOOK_DEBOUNCE_SECS=30
GH_WEBHOOK_LOG_FORMAT=json
EOF
  chmod 600 "${ENV_FILE}"
  echo "Wrote ${ENV_FILE} (mode 0600) with a generated secret."
  echo "  Edit it to set GH_WEBHOOK_GITHUB_TOKEN before registering any repos."
fi

if [[ ! -f "${UNIT_SRC}" ]]; then
  echo "error: systemd unit not found at ${UNIT_SRC}" >&2
  exit 1
fi

install -m 644 "${UNIT_SRC}" "${SERVICE_FILE}"
systemctl --user daemon-reload
systemctl --user enable --now gh-webhook.service

secret="$(sed -n 's/^GH_WEBHOOK_SECRET=//p' "${ENV_FILE}")"

cat <<EOF

gh-webhook.service is installed and running.

To expose it via Tailscale Funnel (path-routed):
  tailscale serve --bg --https=443 --set-path=/gh-webhook http://127.0.0.1:7891
  tailscale funnel --bg --https=443 on

To register a repository (requires GH_WEBHOOK_GITHUB_TOKEN set in env with admin:repo_hook or Webhooks:Write):
  export GH_WEBHOOK_SECRET='${secret}'
  gh-webhook-register --repo OWNER/REPO --url https://<your-host>.ts.net/gh-webhook/webhook

Shared secret (also stored in ${ENV_FILE}):
  ${secret}
EOF
