use lab_apis::core::action::{ActionSpec, ParamSpec};

/// Action catalog for the `jellyfin` service.
pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "system.ping",
        description: "Ping the Jellyfin server",
        destructive: false,
        returns: "String",
        params: &[],
    },
    ActionSpec {
        name: "system.info",
        description: "Fetch authenticated Jellyfin system information",
        destructive: false,
        returns: "SystemInfo",
        params: &[],
    },
    ActionSpec {
        name: "system.public_info",
        description: "Fetch public Jellyfin system information",
        destructive: false,
        returns: "PublicSystemInfo",
        params: &[],
    },
    ActionSpec {
        name: "users.list",
        description: "List Jellyfin users",
        destructive: false,
        returns: "Vec<User>",
        params: &[],
    },
    ActionSpec {
        name: "users.me",
        description: "Fetch the current Jellyfin user",
        destructive: false,
        returns: "User",
        params: &[],
    },
    ActionSpec {
        name: "libraries.list",
        description: "List Jellyfin virtual folders/libraries",
        destructive: false,
        returns: "Vec<VirtualFolder>",
        params: &[],
    },
    ActionSpec {
        name: "items.search",
        description: "Search Jellyfin items with a bounded read-only query subset",
        destructive: false,
        returns: "ItemsResult",
        params: &[
            ParamSpec {
                name: "user_id",
                ty: "string",
                required: false,
                description: "Optional Jellyfin user ID",
            },
            ParamSpec {
                name: "search_term",
                ty: "string",
                required: false,
                description: "Optional item search term",
            },
            ParamSpec {
                name: "parent_id",
                ty: "string",
                required: false,
                description: "Optional parent item/library ID",
            },
            ParamSpec {
                name: "include_item_types",
                ty: "string[]",
                required: false,
                description: "Optional item types such as Movie, Series, Episode",
            },
            ParamSpec {
                name: "recursive",
                ty: "boolean",
                required: false,
                description: "Whether to recurse into child folders",
            },
            ParamSpec {
                name: "start_index",
                ty: "integer",
                required: false,
                description: "Optional zero-based result offset",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: false,
                description: "Optional maximum result count",
            },
        ],
    },
    ActionSpec {
        name: "items.get",
        description: "Fetch one Jellyfin item by ID",
        destructive: false,
        returns: "Item",
        params: &[ParamSpec {
            name: "item_id",
            ty: "string",
            required: true,
            description: "Jellyfin item ID",
        }],
    },
    ActionSpec {
        name: "items.counts",
        description: "Fetch Jellyfin item counts",
        destructive: false,
        returns: "ItemCounts",
        params: &[],
    },
    ActionSpec {
        name: "sessions.list",
        description: "List active Jellyfin sessions",
        destructive: false,
        returns: "Vec<SessionInfo>",
        params: &[],
    },
    ActionSpec {
        name: "plugins.list",
        description: "List installed Jellyfin plugins",
        destructive: false,
        returns: "Vec<PluginInfo>",
        params: &[],
    },
];
