use lab_apis::core::action::{ActionSpec, ParamSpec};

/// Action catalog for upstream OpenACP.
///
/// Product decision: all actions are deliberately `destructive: false`.
pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "system.health",
        description: "Return OpenACP daemon health",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "system.version",
        description: "Return OpenACP daemon version",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "system.restart",
        description: "Request a daemon restart",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "adapters.list",
        description: "List registered channel adapters",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "sessions.list",
        description: "List OpenACP sessions",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "sessions.get",
        description: "Get one OpenACP session",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "session_id",
            ty: "string",
            required: true,
            description: "OpenACP session id",
        }],
    },
    ActionSpec {
        name: "sessions.create",
        description: "Create an OpenACP session",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "agent",
                ty: "string",
                required: false,
                description: "Agent name",
            },
            ParamSpec {
                name: "workspace",
                ty: "string",
                required: false,
                description: "Workspace path",
            },
        ],
    },
    ActionSpec {
        name: "sessions.prompt",
        description: "Enqueue a prompt for a session",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "session_id",
                ty: "string",
                required: true,
                description: "OpenACP session id",
            },
            ParamSpec {
                name: "prompt",
                ty: "string",
                required: true,
                description: "Prompt text",
            },
        ],
    },
    ActionSpec {
        name: "sessions.cancel",
        description: "Cancel an OpenACP session",
        destructive: false,
        returns: "void",
        params: &[ParamSpec {
            name: "session_id",
            ty: "string",
            required: true,
            description: "OpenACP session id",
        }],
    },
    ActionSpec {
        name: "sessions.bypass.set",
        description: "Enable or disable bypass permissions for a session",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "session_id",
                ty: "string",
                required: true,
                description: "OpenACP session id",
            },
            ParamSpec {
                name: "enabled",
                ty: "bool",
                required: true,
                description: "Whether bypass permissions are enabled",
            },
        ],
    },
    ActionSpec {
        name: "sessions.permission.resolve",
        description: "Resolve a pending permission request",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "session_id",
                ty: "string",
                required: true,
                description: "OpenACP session id",
            },
            ParamSpec {
                name: "permission_id",
                ty: "string",
                required: true,
                description: "Permission request id",
            },
            ParamSpec {
                name: "option_id",
                ty: "string",
                required: true,
                description: "Selected permission option id",
            },
        ],
    },
    ActionSpec {
        name: "sessions.archive",
        description: "Archive an OpenACP session",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "session_id",
            ty: "string",
            required: true,
            description: "OpenACP session id",
        }],
    },
    ActionSpec {
        name: "sessions.adopt",
        description: "Adopt an existing external agent session",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "agent",
                ty: "string",
                required: true,
                description: "Agent name",
            },
            ParamSpec {
                name: "agent_session_id",
                ty: "string",
                required: true,
                description: "External agent session id",
            },
            ParamSpec {
                name: "cwd",
                ty: "string",
                required: false,
                description: "Working directory",
            },
            ParamSpec {
                name: "channel",
                ty: "string",
                required: false,
                description: "Channel adapter name",
            },
        ],
    },
    ActionSpec {
        name: "agents.list",
        description: "List configured agents",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "config.get",
        description: "Return upstream-redacted OpenACP config",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "config.editable",
        description: "Return editable config metadata",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "config.patch",
        description: "Patch one safe OpenACP config value",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "path",
                ty: "string",
                required: true,
                description: "Dot-notation config path",
            },
            ParamSpec {
                name: "value",
                ty: "json",
                required: true,
                description: "Config value",
            },
        ],
    },
    ActionSpec {
        name: "topics.list",
        description: "List channel topics",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "status",
            ty: "string",
            required: false,
            description: "Comma-separated status filter",
        }],
    },
    ActionSpec {
        name: "topics.delete",
        description: "Delete the topic for one session",
        destructive: false,
        returns: "void",
        params: &[
            ParamSpec {
                name: "session_id",
                ty: "string",
                required: true,
                description: "OpenACP session id",
            },
            ParamSpec {
                name: "force",
                ty: "bool",
                required: false,
                description: "Delete even if the session is active",
            },
        ],
    },
    ActionSpec {
        name: "topics.cleanup",
        description: "Delete topics matching statuses",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "statuses",
            ty: "array<string>",
            required: false,
            description: "Statuses to clean up",
        }],
    },
    ActionSpec {
        name: "tunnel.status",
        description: "Return primary tunnel status",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "tunnel.list",
        description: "List active user tunnels",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "tunnel.create",
        description: "Create a tunnel to a local port",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "port",
                ty: "integer",
                required: true,
                description: "Local port",
            },
            ParamSpec {
                name: "label",
                ty: "string",
                required: false,
                description: "Display label",
            },
            ParamSpec {
                name: "session_id",
                ty: "string",
                required: false,
                description: "Associated session id",
            },
        ],
    },
    ActionSpec {
        name: "tunnel.delete",
        description: "Stop the tunnel for one local port",
        destructive: false,
        returns: "void",
        params: &[ParamSpec {
            name: "port",
            ty: "integer",
            required: true,
            description: "Local port",
        }],
    },
    ActionSpec {
        name: "tunnel.delete_all",
        description: "Stop all user tunnels",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "notify.send",
        description: "Send a notification to registered channel adapters",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "message",
            ty: "string",
            required: true,
            description: "Notification message",
        }],
    },
];
