use lab_apis::core::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "server.version",
        description: "Return SABnzbd version string",
        destructive: false,
        returns: "string",
        params: &[],
    },
    ActionSpec {
        name: "queue.list",
        description: "List items in the download queue with status and progress",
        destructive: false,
        returns: "QueueResponse",
        params: &[],
    },
    ActionSpec {
        name: "queue.delete",
        description: "Delete an item from the download queue",
        destructive: true,
        returns: "bool",
        params: &[ParamSpec {
            name: "nzo_id",
            ty: "string",
            required: true,
            description: "NZO ID of the queue item to delete",
        }],
    },
    ActionSpec {
        name: "history.list",
        description: "List download history",
        destructive: false,
        returns: "HistoryResponse",
        params: &[ParamSpec {
            name: "limit",
            ty: "integer",
            required: false,
            description: "Max number of history items to return",
        }],
    },
    ActionSpec {
        name: "history.delete",
        description: "Delete a single history item",
        destructive: true,
        returns: "bool",
        params: &[ParamSpec {
            name: "nzo_id",
            ty: "string",
            required: true,
            description: "NZO ID of the history item to delete",
        }],
    },
    ActionSpec {
        name: "history.purge",
        description: "Purge all completed history items",
        destructive: true,
        returns: "bool",
        params: &[],
    },
    ActionSpec {
        name: "server.stats",
        description: "Return download statistics (total/month/week/day)",
        destructive: false,
        returns: "ServerStats",
        params: &[],
    },
    ActionSpec {
        name: "server.warnings",
        description: "List SABnzbd warnings",
        destructive: false,
        returns: "string[]",
        params: &[],
    },
    ActionSpec {
        name: "queue.pause",
        description: "Pause the download queue",
        destructive: false,
        returns: "bool",
        params: &[],
    },
    ActionSpec {
        name: "queue.resume",
        description: "Resume the download queue",
        destructive: false,
        returns: "bool",
        params: &[],
    },
    ActionSpec {
        name: "queue.speed.limit",
        description: "Set the download speed limit in KB/s (0 = unlimited)",
        destructive: false,
        returns: "bool",
        params: &[ParamSpec {
            name: "kbps",
            ty: "integer",
            required: true,
            description: "Speed limit in KB/s (0 to remove limit)",
        }],
    },
];
