use lab_apis::core::action::{ActionSpec, ParamSpec};

pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "server.health",
        description: "Check whether the Qdrant server is healthy",
        destructive: false,
        returns: "void",
        params: &[],
    },
    ActionSpec {
        name: "collections.list",
        description: "List collection names",
        destructive: false,
        returns: "CollectionDescription[]",
        params: &[],
    },
    ActionSpec {
        name: "collections.get",
        description: "Get raw metadata for one collection",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "name",
            ty: "string",
            required: true,
            description: "Collection name",
        }],
    },
    ActionSpec {
        name: "collection.create",
        description: "Create a new collection with vector configuration (PUT /collections/{name})",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "name",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "size",
                ty: "integer",
                required: true,
                description: "Vector dimension size",
            },
            ParamSpec {
                name: "distance",
                ty: "string",
                required: true,
                description: "Distance metric: Cosine, Euclid, Dot, or Manhattan",
            },
        ],
    },
    ActionSpec {
        name: "collection.delete",
        description: "Delete a collection and all its data (DELETE /collections/{name})",
        destructive: true,
        returns: "void",
        params: &[ParamSpec {
            name: "name",
            ty: "string",
            required: true,
            description: "Collection name to delete",
        }],
    },
    ActionSpec {
        name: "point.upsert",
        description: "Upsert points into a collection (PUT /collections/{name}/points). Large batches auto-chunked at 500 points/chunk. Pass returned rid on subsequent calls.",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Target collection name",
            },
            ParamSpec {
                name: "points",
                ty: "array",
                required: true,
                description: "Array of points: [{id, vector, payload?}]",
            },
        ],
    },
    ActionSpec {
        name: "point.search",
        description: "Search for nearest neighbours (POST /collections/{name}/points/search)",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name to search",
            },
            ParamSpec {
                name: "vector",
                ty: "array",
                required: true,
                description: "Query vector (array of floats)",
            },
            ParamSpec {
                name: "limit",
                ty: "integer",
                required: true,
                description: "Maximum number of results to return",
            },
            ParamSpec {
                name: "filter",
                ty: "object",
                required: false,
                description: "Optional Qdrant filter expression",
            },
            ParamSpec {
                name: "with_payload",
                ty: "bool",
                required: false,
                description: "Whether to include payload in results (default: false)",
            },
            ParamSpec {
                name: "score_threshold",
                ty: "number",
                required: false,
                description: "Minimum score threshold for results",
            },
        ],
    },
    ActionSpec {
        name: "point.query",
        description: "Universal query endpoint (POST /collections/{name}/points/query). Accepts any Qdrant query body.",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "query",
                ty: "object",
                required: true,
                description: "Full Qdrant query body (passed through as-is)",
            },
        ],
    },
    ActionSpec {
        name: "point.scroll",
        description: "Scroll through points in a collection (POST /collections/{name}/points/scroll)",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "scroll",
                ty: "object",
                required: false,
                description: "Scroll request body (limit, offset, filter, with_payload, etc.)",
            },
        ],
    },
    ActionSpec {
        name: "point.count",
        description: "Count points matching an optional filter (POST /collections/{name}/points/count)",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "filter",
                ty: "object",
                required: false,
                description: "Optional filter expression",
            },
        ],
    },
    ActionSpec {
        name: "point.delete",
        description: "Delete points by ids or filter (POST /collections/{name}/points/delete)",
        destructive: true,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "points",
                ty: "array",
                required: false,
                description: "Array of point ids to delete",
            },
            ParamSpec {
                name: "filter",
                ty: "object",
                required: false,
                description: "Filter expression to select points for deletion",
            },
        ],
    },
    ActionSpec {
        name: "snapshot.create",
        description: "Create a collection snapshot (POST /collections/{name}/snapshots)",
        destructive: false,
        returns: "SnapshotInfo",
        params: &[ParamSpec {
            name: "collection",
            ty: "string",
            required: true,
            description: "Collection name",
        }],
    },
    ActionSpec {
        name: "index.create",
        description: "Create a payload field index (PUT /collections/{name}/index)",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "collection",
                ty: "string",
                required: true,
                description: "Collection name",
            },
            ParamSpec {
                name: "field_name",
                ty: "string",
                required: true,
                description: "Payload field name to index",
            },
            ParamSpec {
                name: "field_schema",
                ty: "object",
                required: true,
                description: "Field schema type (e.g. \"keyword\", \"integer\", or schema object)",
            },
        ],
    },
];
