use lab_apis::core::action::{ActionSpec, ParamSpec};

/// Action catalog for the `ByteStash` service.
///
/// This is the single authoritative source. MCP, CLI, and API re-export
/// or reference it.
pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "auth.config",
        description: "Get auth provider configuration",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "auth.register",
        description: "Register a new user",
        destructive: true,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "username",
                ty: "string",
                required: true,
                description: "Username",
            },
            ParamSpec {
                name: "password",
                ty: "string",
                required: true,
                description: "Password",
            },
            ParamSpec {
                name: "payload",
                ty: "json",
                required: false,
                description: "Alternative: full JSON body (overrides individual params)",
            },
        ],
    },
    ActionSpec {
        name: "auth.login",
        description: "Log in and receive a JWT",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "username",
                ty: "string",
                required: true,
                description: "Username",
            },
            ParamSpec {
                name: "password",
                ty: "string",
                required: true,
                description: "Password",
            },
            ParamSpec {
                name: "payload",
                ty: "json",
                required: false,
                description: "Alternative: full JSON body (overrides individual params)",
            },
        ],
    },
    ActionSpec {
        name: "snippets.list",
        description: "List the caller's snippets",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "snippets.get",
        description: "Get one snippet",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "string",
            required: true,
            description: "Snippet ID",
        }],
    },
    ActionSpec {
        name: "snippets.create",
        description: "Create a snippet",
        destructive: true,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "title",
                ty: "string",
                required: true,
                description: "Snippet title",
            },
            ParamSpec {
                name: "description",
                ty: "string",
                required: false,
                description: "Optional description",
            },
            ParamSpec {
                name: "language",
                ty: "string",
                required: false,
                description: "Optional language label",
            },
            ParamSpec {
                name: "fragments",
                ty: "json",
                required: false,
                description: "Snippet fragments JSON",
            },
            ParamSpec {
                name: "categories",
                ty: "json",
                required: false,
                description: "Category list JSON",
            },
            ParamSpec {
                name: "payload",
                ty: "json",
                required: false,
                description: "Alternative: full JSON body (overrides individual params)",
            },
        ],
    },
    ActionSpec {
        name: "snippets.update",
        description: "Update a snippet",
        destructive: true,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "id",
                ty: "string",
                required: true,
                description: "Snippet ID",
            },
            ParamSpec {
                name: "title",
                ty: "string",
                required: false,
                description: "Snippet title",
            },
            ParamSpec {
                name: "description",
                ty: "string",
                required: false,
                description: "Optional description",
            },
            ParamSpec {
                name: "language",
                ty: "string",
                required: false,
                description: "Optional language label",
            },
            ParamSpec {
                name: "fragments",
                ty: "json",
                required: false,
                description: "Snippet fragments JSON",
            },
            ParamSpec {
                name: "categories",
                ty: "json",
                required: false,
                description: "Category list JSON",
            },
            ParamSpec {
                name: "payload",
                ty: "json",
                required: false,
                description: "Alternative: full JSON body (overrides individual params)",
            },
        ],
    },
    ActionSpec {
        name: "snippets.delete",
        description: "Delete a snippet",
        destructive: true,
        returns: "void",
        params: &[ParamSpec {
            name: "id",
            ty: "string",
            required: true,
            description: "Snippet ID",
        }],
    },
    ActionSpec {
        name: "snippets.public.list",
        description: "List public snippets",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "snippets.public.get",
        description: "Get one public snippet",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "string",
            required: true,
            description: "Public snippet ID",
        }],
    },
    ActionSpec {
        name: "snippets.share.create",
        description: "Create a share link for a snippet",
        destructive: true,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "snippetId",
                ty: "string",
                required: true,
                description: "Snippet ID to share",
            },
            ParamSpec {
                name: "requiresAuth",
                ty: "bool",
                required: false,
                description: "Whether the link requires auth to view",
            },
            ParamSpec {
                name: "expiresIn",
                ty: "integer",
                required: false,
                description: "Expiry in seconds (null = never)",
            },
            ParamSpec {
                name: "payload",
                ty: "json",
                required: false,
                description: "Alternative: full JSON body (overrides individual params)",
            },
        ],
    },
    ActionSpec {
        name: "snippets.share.get",
        description: "Get a shared snippet",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "share_id",
            ty: "string",
            required: true,
            description: "Share link ID",
        }],
    },
    ActionSpec {
        name: "categories.list",
        description: "List snippet metadata including all categories in use",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "users.list",
        description: "List users",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "users.toggle-active",
        description: "Toggle a user's active status (admin only)",
        destructive: true,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "string",
            required: true,
            description: "User ID",
        }],
    },
    ActionSpec {
        name: "users.delete",
        description: "Delete a user",
        destructive: true,
        returns: "void",
        params: &[ParamSpec {
            name: "id",
            ty: "string",
            required: true,
            description: "User ID",
        }],
    },
];
