use lab_apis::core::action::{ActionSpec, ParamSpec};

/// Action catalog for the `Prowlarr` service.
///
/// This is the single authoritative source. MCP, CLI, and API re-export
/// or reference it.
pub const ACTIONS: &[ActionSpec] = &[
    ActionSpec {
        name: "help",
        description: "Show this action catalog",
        destructive: false,
        returns: "Catalog",
        params: &[],
    },
    ActionSpec {
        name: "schema",
        description: "Return the parameter schema for a named action",
        destructive: false,
        returns: "Schema",
        params: &[ParamSpec {
            name: "action",
            ty: "string",
            required: true,
            description: "Action name to describe",
        }],
    },
    ActionSpec {
        name: "indexer.list",
        description: "List all configured indexers",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "indexer.get",
        description: "Get a single indexer by ID",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Indexer ID",
        }],
    },
    ActionSpec {
        name: "indexer.delete",
        description: "Delete an indexer by ID",
        destructive: true,
        returns: "void",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Indexer ID",
        }],
    },
    ActionSpec {
        name: "indexer.test",
        description: "Test a single indexer by ID (fetches the indexer then POSTs to test endpoint)",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Indexer ID",
        }],
    },
    ActionSpec {
        name: "indexer.testall",
        description: "Test all configured indexers",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "indexer.categories",
        description: "List all indexer categories",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "history.list",
        description: "Get history with optional filters",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "page",
                ty: "integer",
                required: false,
                description: "Page number (1-based)",
            },
            ParamSpec {
                name: "page_size",
                ty: "integer",
                required: false,
                description: "Number of results per page",
            },
            ParamSpec {
                name: "sort_key",
                ty: "string",
                required: false,
                description: "Field to sort by (e.g. date)",
            },
            ParamSpec {
                name: "sort_dir",
                ty: "string",
                required: false,
                description: "Sort direction: ascending or descending",
            },
            ParamSpec {
                name: "indexer_id",
                ty: "integer",
                required: false,
                description: "Filter history to a specific indexer ID",
            },
        ],
    },
    ActionSpec {
        name: "application.list",
        description: "List configured applications (download clients connected to Prowlarr)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "application.get",
        description: "Get a single application by ID",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Application ID",
        }],
    },
    ActionSpec {
        name: "application.delete",
        description: "Delete an application by ID",
        destructive: true,
        returns: "void",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Application ID",
        }],
    },
    ActionSpec {
        name: "indexer.edit",
        description: "Update an existing indexer by ID (PUT /api/v1/indexer/{id})",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "id",
                ty: "integer",
                required: true,
                description: "Indexer ID",
            },
            ParamSpec {
                name: "body",
                ty: "object",
                required: true,
                description: "Full indexer resource object to update",
            },
        ],
    },
    ActionSpec {
        name: "indexer.add",
        description: "Create a new indexer (POST /api/v1/indexer)",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "body",
            ty: "object",
            required: true,
            description: "Indexer resource object to create",
        }],
    },
    ActionSpec {
        name: "indexer.stats",
        description: "Get indexer statistics (GET /api/v1/indexerstats)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "indexer.status",
        description: "Get indexers with errors (GET /api/v1/indexerstatus)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "indexer.search",
        description: "Search across indexers (GET /api/v1/search)",
        destructive: false,
        returns: "Value",
        params: &[
            ParamSpec {
                name: "query",
                ty: "string",
                required: true,
                description: "Search query string",
            },
            ParamSpec {
                name: "indexer_ids",
                ty: "array[integer]",
                required: false,
                description: "List of indexer IDs to search (empty = all)",
            },
            ParamSpec {
                name: "categories",
                ty: "array[integer]",
                required: false,
                description: "List of category IDs to filter by",
            },
            ParamSpec {
                name: "search_type",
                ty: "string",
                required: false,
                description: "Search type (default: search)",
            },
        ],
    },
    ActionSpec {
        name: "indexer.grab",
        description: "Grab a release by GUID and send to download client (POST /api/v1/search)",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "guid",
            ty: "string",
            required: true,
            description: "Release GUID to grab",
        }],
    },
    ActionSpec {
        name: "history.indexer",
        description: "Get history for a specific indexer (GET /api/v1/history?indexerId={id})",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "id",
            ty: "integer",
            required: true,
            description: "Indexer ID to get history for",
        }],
    },
    ActionSpec {
        name: "application.add",
        description: "Create a new application (POST /api/v1/applications)",
        destructive: false,
        returns: "Value",
        params: &[ParamSpec {
            name: "body",
            ty: "object",
            required: true,
            description: "Application resource object to create",
        }],
    },
    ActionSpec {
        name: "system.restart",
        description: "Restart the Prowlarr server (POST /api/v1/system/restart)",
        destructive: true,
        returns: "void",
        params: &[],
    },
    ActionSpec {
        name: "system.backup",
        description: "Get system backups (GET /api/v1/system/backup)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "tag.list",
        description: "List all tags (GET /api/v1/tag)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "system.status",
        description: "Get system status (version, branch, OS, etc.)",
        destructive: false,
        returns: "Value",
        params: &[],
    },
    ActionSpec {
        name: "system.health",
        description: "Get system health alerts",
        destructive: false,
        returns: "Value",
        params: &[],
    },
];
